/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Application: (typeof import('./src/components/Application/Application.vue'))['default']
    NAutoComplete: (typeof import('naive-ui'))['NAutoComplete']
    NAvatar: (typeof import('naive-ui'))['NAvatar']
    NBackTop: (typeof import('naive-ui'))['NBackTop']
    NButton: (typeof import('naive-ui'))['NButton']
    NCard: (typeof import('naive-ui'))['NCard']
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider']
    NDataTable: (typeof import('naive-ui'))['NDataTable']
    NDatePicker: (typeof import('naive-ui'))['NDatePicker']
    NDropdown: (typeof import('naive-ui'))['NDropdown']
    NEmpty: (typeof import('naive-ui'))['NEmpty']
    NFlex: (typeof import('naive-ui'))['NFlex']
    NFormItem: (typeof import('naive-ui'))['NFormItem']
    NGrid: (typeof import('naive-ui'))['NGrid']
    NGridItem: (typeof import('naive-ui'))['NGridItem']
    NH2: (typeof import('naive-ui'))['NH2']
    NIcon: (typeof import('naive-ui'))['NIcon']
    NInput: (typeof import('naive-ui'))['NInput']
    NInputGroup: (typeof import('naive-ui'))['NInputGroup']
    NInputNumber: (typeof import('naive-ui'))['NInputNumber']
    NLayout: (typeof import('naive-ui'))['NLayout']
    NLayoutContent: (typeof import('naive-ui'))['NLayoutContent']
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader']
    NLayoutSider: (typeof import('naive-ui'))['NLayoutSider']
    NMenu: (typeof import('naive-ui'))['NMenu']
    NNumberAnimation: (typeof import('naive-ui'))['NNumberAnimation']
    NPagination: (typeof import('naive-ui'))['NPagination']
    NProgress: (typeof import('naive-ui'))['NProgress']
    NSelect: (typeof import('naive-ui'))['NSelect']
    NSkeleton: (typeof import('naive-ui'))['NSkeleton']
    NSpace: (typeof import('naive-ui'))['NSpace']
    NTabPane: (typeof import('naive-ui'))['NTabPane']
    NTabs: (typeof import('naive-ui'))['NTabs']
    NTag: (typeof import('naive-ui'))['NTag']
    NText: (typeof import('naive-ui'))['NText']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    TimeSeriesPathAutoCompletion: (typeof import('./src/components/TimeSeriesPathAutoCompletion.vue'))['default']
    TimeSeriesTimeOverview: (typeof import('./src/components/TimeSeriesTimeOverview.vue'))['default']
    TimeSeriesTimeRangePicker: (typeof import('./src/components/TimeSeriesTimeRangePicker.vue'))['default']
  }
}
